apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        env:
        - name: POSTGRES_DB
          value: appdb
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin123
        ports:
        - containerPort: 5432