apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: fullstack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: vineetsaini13/user-service:v1
        env:
        - name: PORT
          value: "3001"
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: microservices_db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: JWT_SECRET
          value: dev-secret-change-me
        ports:
        - containerPort: 3001